import React from "react";

function TermAndCondition(props) {
  return (
    <div className="container mb-4 ">
      <div className="termCondition">
        {" "}
        <h1>TERMS AND CONDITIONS</h1>
        <p className="mb-2">
          {" "}
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules there under as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <p>
          {" "}
          You agree to the terms and conditions for limited customization and
          circulation of the EDM (as defined hereinafter) to the Permitted
          Recipients (as defined hereinafter):
        </p>
        <ol>
          <li>
            <span>
              These terms and conditions ("Terms") govern your ("you" or "your")
              usage of RayBan Electronic Direct Mailer ("EDM") provided or made
              available to you by Luxottica India Eyewear Pvt. Ltd.
              (collectively Company", "we", "us" or "our" or "Ours").
            </span>
          </li>
          <li>
            <span>
              All the rights (including intellectual property rights, moral
              rights) in the EDM are reserved in favour of Luxottica India
              Eyewear Pvt. Ltd. and its group / affiliate companies / licensors
              except as provided under these Terms.
            </span>
          </li>
          <li>
            <span>
              You will have a limited personal, non-transferable,
              non-sublicensable, revocable right to customize the EDM only by
              adding your Optical store name, store details, contact number &
              details, email id, trademark / logo / visiting card only through
              the facility provided at https://myemailer.in/. You cannot use any
              other tool / software / application etc. to customize or edit the
              EDM or use it in any manner other than as authorised under these
              Terms.
            </span>
          </li>
          <li>
            <span>
              {" "}
              You may circulate or send the EDM, at your costs, risks and
              responsibility, only to your customers, partners, employees,
              representatives ("Permitted Recipients") only with limited right
              to read, archive the EDM and use it for personal purposes only.
            </span>
          </li>
          <li>
            <span>
              You will not edit, modify, translate, copy, host, publicly
              display, reproduce, republish or use the EDM or any content
              thereof (except as provided by you) in any manner except as
              provided under these Terms.
            </span>
          </li>
          <li>
            <span>
              By sending, forwarding, sharing or in any other providing EDM to
              Permitted Recipients, You hereby confirm and state that you have
              received written consent from your customers for receiving the EDM
              including providing them an option of opting out/unsubscribe. You
              shall comply with all applicable law including but not limited to
              Information Technology Act, 2000, Information Technology
              (Reasonable security practices and procedures and sensitive
              personal data or information) Rules, 2011, data privacy laws,
              developing your own privacy policy for dealing with the personal
              information collected pursuant to circulation of the EDM and other
              obligations under these Terms and the Applicable Laws.
            </span>
          </li>
          <li>
            <span>
              {" "}
              You understand that you, and not We, are responsible for all
              electronic communications and content sent from your computer,
              smart phones or other digital / electronic devices to the
              permitted Recipients. You must use the EDM for lawful and ethical
              purposes only. You must not use the EDM for any fraudulent,
              offensive, illegal, deceptive, misleading, defamatory,
              objectionable, disparaging purposes or in violation of rights of
              privacy, breach of intellectual property rights or in other
              injurious or harmful way or to impersonate anyone.
            </span>
          </li>
          <li>
            <span>
              {" "}
              Use of information contained in the EDM is at your own risk and We
              are not responsible for any adverse consequences arising out of
              such use. You assume sole risk and responsibility for anything
              arising from your use of the EDM.
            </span>
          </li>
          <li>
            <span>
              We reserve the sole right to either modify or discontinue the EDM,
              at any time with or without notice to you. We will not be liable
              to you or any third party should we exercise such right.
            </span>
          </li>
          <li>
            <span>
              The Company reserves the right, at its discretion, to suspend or
              cancel your rights granted under these Terms at any time for any
              reasons including breach of these terms, without any notice to you
              and without any obligation to you.
            </span>
          </li>
          <li>
            <span>
              {" "}
              Any unauthorized use of any content or materials in this EDM is
              strictly prohibited and may violate copyright and trademark laws
              and/or the laws of privacy, publicity, and/or communications
              regulations and statutes. Any use of the materials or content in
              this EDM can be made only with the prior written and express
              authorization of Ours. Nothing contained in the EDM or Terms
              should be construed as granting, by implication or otherwise, any
              right, license or title to any of the Company's Intellectual
              Property and/or Third Party Intellectual Property.
            </span>
          </li>
          <li>
            <span>
              THIS EDM AND ALL CONTENTS (INCLUDING PRODUCT DESCRIPTIONS,
              INFORMATION AND MATERIALS) THEREIN ARE PROVIDED ON AN "AS IS"
              BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
              WE DISCLAIM ANY AND ALL WARRANTIES OF ANY KIND, EITHER EXPRESS OR
              IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED AND/OR EXPRESS
              WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR
              PURPOSE AND NON-INFRINGEMENT. WE MAKE NO REPRESENTATIONS OR
              WARRANTIES THAT THIS EDM AND/OR ITS CONTENTS ARE ACCURATE,
              COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WE ARE NOT RESPONSIBLE
              FOR TYPOGRAPHICAL ERRORS OR OMISSIONS RELATING TO TEXT,
              PHOTOGRAPHY OR ANY OTHER CONTENTS ON THIS EDM.
            </span>
          </li>
          <li>
            <span>
              WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT THIS EDM ARE FREE OF
              VIRUSES OR OTHER HARMFUL COMPONENTS. WE MAKES NO REPRESENTATIONS
              OR WARRANTIES THAT THIS EDM FACILITY WILL BE CONSTANTLY AVAILABLE
              OR AVAILABLE AT ALL.
            </span>
          </li>
          <li>
            <span>
              IN NO EVENT SHALL WE, OUR PARENT, SUBSIDIARIES OR AFFILIATES BE
              LIABLE FOR ANY DIRECT, SPECIAL, PUNITIVE, EXEMPLARY, INDIRECT OR
              CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING
              BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS, OR LOSS OF DATA,
              WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED
              TO NEGLIGENCE), OR OTHERWISE, ARISING OUT OF OR IN ANY WAY
              CONNECTED WITH THE USE OR INABILITY TO USE THIS EDM OR THE
              MATERIALS CONTAINED THEREIN. IN NO EVENT SHALL THE AGGREGATE
              LIABILITY OF OURS, OUR PARENT, SUBSIDIARIES OR AFFILIATES (WHETHER
              IN CONTRACT, WARRANTY, TORT (INCLUDING BUT NOT LIMITED TO
              NEGLIGENCE), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY)
              ARISING OUT OF OR RELATING TO THE USE OF THIS EDM EXCEED INR 100.
            </span>
          </li>
          <li>
            <span>
              You shall fully defend, indemnify and hold harmless Company, its
              group companies, affiliates, directors, employees, service
              providers, representatives etc. from and against any liability,
              claim, expenses, fees (including attorney fees),charges, fines,
              penalties, damages or any other monetary or non- monetary
              liability claimed or alleged or imposed upon us arising by way of
              non-compliance of applicable laws, breach of these terms and
              conditions, infringement of intellectual property rights or any
              third party rights, breach of privacy, confidentiality, any
              action, omission, negligence etc., use or misuse of the EDM by you
              or permitted Recipients or any other event giving rise to a third
              party claim.
            </span>
          </li>
          <li>
            <span>
              {" "}
              These Terms will be governed by the laws of India. Further, the
              courts at Gurugram shall have exclusive jurisdiction for all
              matters arising out of or in connection with these Terms and you
              agree to irrevocably submit to the exclusive jurisdiction of such
              courts.
            </span>
          </li>
          <li>
            <span>
              {" "}
              The Company reserves the right, at any time and from time to time,
              to amend, modify, revise, update, suspend and/or otherwise change
              these Terms without prior notice to you.
            </span>
          </li>
          <li>
            <span>General</span>
          </li>
        </ol>
        <div className="m-2">
          <p>
            (a)
            <span>
              If any provision of these Terms is held to be invalid, illegal or
              unenforceable, such provision will be struck from these Terms and
              the remaining provisions of these Terms shall remain in full force
              and effect.
            </span>
          </p>
          <p>
            (b)
            <span>
              No failure on the part of the Company to exercise or delay in
              exercising any right hereunder will be deemed a waiver thereof,
              nor will any single or partial exercise preclude any further or
              other exercise of such or any other right.
            </span>
          </p>
          <p>
            (c)
            <span>
              These Terms constitutes the entire agreement between you and the
              Company relating to the subject matter hereof.
            </span>
          </p>
          <p>
            (d)
            <span>
              Any notices required to be provided to you under these Terms may
              be made via email or such other mode as may be determined by the
              Company.
            </span>
          </p>
        </div>
        <p>Contact</p>
        <p className="mb-2">You may contact us at the following address</p>
        <p>Luxottica India Eyewear Private Limited</p>
        <p>7th Floor, DLF Building No. 9, Tower - B</p>
        <p>DLF Cyber City, Phase - III, Gurugram - 122002, Haryana</p>
        <p>Luxottica.india@in.luxottica.com</p>
      </div>
    </div>
  );
}

export default TermAndCondition;
