export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SEND_OTP_REQUEST = "USER_LOGIN_SEND_OTP_REQUEST";
export const USER_LOGIN_SEND_OTP_SUCCESS = "USER_LOGIN_SEND_OTP_SUCCESS";
export const USER_LOGIN_SEND_OTP_FAIL = "USER_LOGIN_SEND_OTP_FAIL";
