export const STORE_SUCCESS = "STORE_SUCCESS";
export const STORE_REQUEST = "STORE_REQUEST";
export const STORE_FAIL = "STORE_FAIL";

export const FIND_STORE_SUCCESS = "FIND_STORE_SUCCESS";
export const FIND_STORE_REQUEST = "FIND_STORE_REQUEST";
export const FIND_STORE_FAIL = "FIND_STORE_FAIL";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";

export const FIND_STOREBYID_SUCCESS = "FIND_STOREBYID_SUCCESS";
export const FIND_STOREBYID_REQUEST = "FIND_STOREBYID_REQUEST";
export const FIND_STOREBYID_FAIL = "FIND_STOREBYID_FAIL";

export const SEND_IMAGETOEMAIL_REQUEST = "SEND_IMAGETOEMAIL_REQUEST";
export const SEND_IMAGETOEMAIL_SUCCESS = "SEND_IMAGETOEMAIL_SUCCESS";
export const SEND_IMAGETOEMAIL_FAIL = "SEND_IMAGETOEMAIL_FAIL";

export const SEND_IMAGETOWHATSAPP_REQUEST = "SEND_IMAGETOWHATSAPP_REQUEST";
export const SEND_IMAGETOWHATSAPP_SUCCESS = "SEND_IMAGETOWHATSAPP_SUCCESS";
export const SEND_IMAGETOWHATSAPP_FAIL = "SEND_IMAGETOWHATSAPP_FAIL";

export const UPDATE_STOREBYID_SUCCESS = "UPDATE_STOREBYID_SUCCESS";
export const UPDATE_STOREBYID_REQUEST = "UPDATE_STOREBYID_REQUEST";
export const UPDATE_STOREBYID_FAIL = "UPDATE_STOREBYID_FAIL";
